# Coursework Component 2
*Instructions*: In this coursework, you will show your domain of the data related Python skills required for business analytics. To do so, you will use packages such as pandas and matplotlib.

## Importing and Visualising a Business Case in Python
Each student will be assigned a different dataset in a different format. The goal is to import the dataset into Python so that you can wrangle and visualise the data in better ways. This will allow you to get your own conclusions and start building up knowledge regarding on how you could potentially learn from data to predict or classify future instances.

You must create a program which allows you to select the following options:
1. Import your dataset into the Python environment.
2. Query and print an instance of the dataset (by row number or by row name).
3. Create a new dataset with less columns by indicating a list of columns to bring upon a new reduced dataset.
4. Randomly split the dataset into two substes called *training* and *testing* according to a ratio specified by the user.
5. Visualise a dataset using a scatterplot which relates two variables specified by the user.
    1. The user shall also be capable to specify the chart title and the $x$ and $y$ labels, as well as a fixed colour and size for the dots in the plot.
    2. Alternatively, the user may SPECIFY the *TARGET/CLASS* column as the colour differentiator. If that is the case, then the program has to show the user the targets/classes and ask the user to specify a colour for each target/class.
6. Exit the program.

## Additional Considerations
* The program has to check that every input option added by the user is valid.
* No option can be executed until option 1 is executed first.
* Whenever a dataset or subdataset is imported or created, print it for the user to visually inspect it.
* In option 2, the row to query can be specified either using the row number or the row name.
* In option 3, the list of columns has to be specified by column name.
* Option 5 can receive as input either the original dataset or the training/testing ones (if these have been already created).

## Submission Instructions

* Once that you have finished your program, run all cells and run the main program cell using the sequence of options 0-2-1-2-3-4-5-6 (option 0 is purposely created to verify that your program can handle the error). 
* Then, without clearing the kernel, generate a html **OR** pdf file from the Jupyter notebook. 
* Name both the Jupyter notebook and the html/pdf file with your id number and submit them to the corresponding Moodle's dropbox before **12th December, 2019**.

In [6]:
## Use this cell to import all necessary packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
## Use this cell to define the function corresponding to OPTION 1
def option1():
    '''With this function you import the dataset.'''
    dataset = pd.read_csv('iris.csv')
    print('The dataset has been imported!')
    print(dataset)
    return dataset

In [36]:
## Use this cell to define the function corresponding to OPTION 2

def option2(dataset):
    '''This function queries and prints an instance of the dataset.'''
    ans = True
    while ans:
        print('Select 1 to query by row number or 2 to query by row name:')
        ans = input('>> ')
        if ans=='1' or ans =='2':
            if ans=='1':
                ans2 = True
                while ans2:
                    print('Select the row number to query (indexes start in 0):')
                    ans2 = input('>> ')
                    if int(ans2)<=len(dataset)-1:
                        print(dataset.iloc[int(ans2)])
                        ans2 = False
                    else:
                        print('The index number is unvalid. Please try again.')
            else:
                ans2 = True
                while ans2:
                    print('Select the row index to query:')
                    ans2 = input('>> ')
                    if ans2 in dataset.index:
                        print(dataset.loc[ans2])
                        ans2 = False
                    else:
                        print('The index name is unvalid. Please try again.')
            ans = False
        else:
            print('Wrong option. Please try again.')
    return

In [16]:
## Use this cell to define the function corresponding to OPTION 3

def option3(dataset):
    '''This function creates a new dataset by indicating which columns to remove.'''
    columnstoinclude=[]
    ans = True
    while ans:
        print('Indicate a column to ignore:')
        print(list(dataset.columns))
        ans = input('>> ')
        if ans in dataset.columns:
            columnstoinclude.append(ans)
            print('Do you want to indicate another column? (Y/N)')
            ans2 = True
            while ans2:
                ans2 = input('>> ')
                if ans2.lower()=='y':
                    ans2=False
                elif ans2.lower()=='n':
                    ans2=False
                    ans=False
                else:
                    print('Wrong option. Please try again.')            
        else:
            print('The column indicated does not exit. Please try again.')
    if columnstoinclude:
        dataset_reduced = dataset[columnstoinclude]
        print(dataset_reduced)
    return dataset_reduced

In [18]:
reduced_dataset

     sepal.length  petal.width
0             5.1          0.2
1             4.9          0.2
2             4.7          0.2
3             4.6          0.2
4             5.0          0.2
5             5.4          0.4
6             4.6          0.3
7             5.0          0.2
8             4.4          0.2
9             4.9          0.1
10            5.4          0.2
11            4.8          0.2
12            4.8          0.1
13            4.3          0.1
14            5.8          0.2
15            5.7          0.4
16            5.4          0.4
17            5.1          0.3
18            5.7          0.3
19            5.1          0.3
20            5.4          0.2
21            5.1          0.4
22            4.6          0.2
23            5.1          0.5
24            4.8          0.2
25            5.0          0.2
26            5.0          0.4
27            5.2          0.2
28            5.2          0.2
29            4.7          0.2
..            ...          ...
120           6.9          2.3
121           5.6          2.0
122           7.7          2.0
123           6.3          1.8
124           6.7          2.1
125           7.2          1.8
126           6.2          1.8
127           6.1          1.8
128           6.4          2.1
129           7.2          1.6
130           7.4          1.9
131           7.9          2.0
132           6.4          2.2
133           6.3          1.5
134           6.1          1.4
135           7.7          2.3
136           6.3          2.4
137           6.4          1.8
138           6.0          1.8
139           6.9          2.1
140           6.7          2.4
141           6.9          2.3
142           5.8          1.9
143           6.8          2.3
144           6.7          2.5
145           6.7          2.3
146           6.3          1.9
147           6.5          2.0
148           6.2          2.3
149           5.9          1.8

[150 rows x 2 columns]

In [ ]:
## Use this cell to define the function corresponding to OPTION 4

def option4():
    '''This function'''
    return

In [ ]:
## Use this cell to define the function corresponding to OPTION 4

def option5():
    '''This function'''
    return

In [ ]:
## Use this cell to create the "main" part of your program
print('Welcome to ***NAME AND ID*** business case.')

## Questions
Please answer the following questions to appraise your level of engagement with the content of the course. Use the Markdown cell corresponding to each question to write your answers.

1. In the dataset that was assigned to you, did you notice any two variables that were correlated or that allowed the dataset to be clustered into groups?

**ANSWER:**

In [ ]:
# Use this cell to plot a scatterplot of your dataset which supports your answer.

2. Describe how a linear regression could be used to predict the values of new data.

**ANSWER:**

In [ ]:
# Use this cell if you want to show how to implement a linear regression in your dataset.

3. Describe how a clustering algorithm (such as hierarchical or k-means) could allow to cluster data into groups.

**ANSWER:**

In [ ]:
# Use this cell if you want to show how to implement clustering in your dataset.